# .percy.yml
version: 2
snapshot:
  widths:
    - 576 ##small mobile
    - 992 ##large desktop
storybook:
  waitForTimeout: 3
  waitForSelector: ''
  additionalSnapshots: []
  include: []
  exclude: []