version: "3.7"

services:
  cypress:
    networks:
      network:
    image: cypress/included:10.4.0
    working_dir: /app
    volumes:
      - .:/app:delegated
    entrypoint: /app/node_modules/cypress/bin/cypress run --component

networks:
  network:
