version: "3.7"

services:
  server:
    hostname: server
    networks:
      network:
        aliases:
          - cruk-react-components
    expose:
      - "8080"
    ports:
      - 8080:8080
    image: node:16.5.0-buster
    volumes:
      - .:/app:delegated
    working_dir: /app
    entrypoint: "/app/node_modules/webpack/bin/webpack.js server --config webpack.config.docs.js --mode development"
  cypress:
    environment:
      - npm_config_unsafe_perm=true
    networks:
      network:
    image: cypress/included:9.4.1
    working_dir: /app
    volumes:
      - .:/app:delegated
    entrypoint: npx cypress run-ct

networks:
  network:
