version: '3.7'

services:
  npm:
    image: node:14
    volumes:
      - .:/app:delegated
    working_dir: /app
    entrypoint: '/usr/local/bin/npm install'
  server:
    hostname: server
    networks:
      network:
        aliases:
          - cruk-react-components
    expose:
      - '8080'
    ports:
      - 8080:8080
    image: node
    volumes:
      - .:/app:delegated
    working_dir: /app
    entrypoint: '/app/node_modules/webpack/bin/webpack.js server --config webpack.config.docs.js --mode development'
  cypress:
    networks:
      network:
    image: cypress/included:8.4.1
    working_dir: /app
    volumes:
      - .:/app:delegated
    entrypoint: npx cypress run-ct

networks:
  network:
