version: "3.7"

services:
  npm:
    image: node:16
    volumes:
      - .:/app:delegated
    working_dir: /app
    entrypoint: "/usr/local/bin/npm install"
    environment:
      CYPRESS_CACHE_FOLDER: ./cy-cache
  server:
    hostname: server
    networks:
      network:
        aliases:
          - cruk-react-components
    expose:
      - "8080"
    ports:
      - 8080:8080
    image: node:16
    volumes:
      - .:/app:delegated
    working_dir: /app
    entrypoint: "/app/node_modules/webpack/bin/webpack.js server --config webpack.config.docs.js --mode development"
    environment:
      CYPRESS_CACHE_FOLDER: ./cy-cache
  cypress:
    networks:
      network:
    image: cypress/included:8.7.0
    working_dir: /app
    volumes:
      - .:/app:delegated
    entrypoint: npx cypress run-ct
    environment:
      CYPRESS_CACHE_FOLDER: ./cy-cache

networks:
  network:
