name: publish to github pages

on:
  push:
    branches:
      - master

jobs:
  apply:
    name: publish to github pages
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2-beta
      - name: npm ci
        run: npm ci
      - name: npm run build
        run: npm run build && touch dist/.nojekyll
      - name: publish to github pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
