name: "Test"
on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  Cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cruk-react-components
        uses: actions/checkout@v3
      - name: npm install
        run: docker-compose run --entrypoint=npm cypress ci
      - name: Test
        run: docker-compose run cypress
      - name: Work around our usage of Github storage
        if: failure()
        run: |
          mkdir output
          tar cvfj output/screenshots.tar.bz2 -C cypress/screenshots .
          tar cvfj output/snapshots.tar.bz2 -C cypress/snapshots .
      - name: Upload Cypress output
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: output
  Jest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cruk-react-components
        uses: actions/checkout@v3
      - name: npm install
        run: npm ci --legacy-peer-deps
      - name: Test
        run: npm run jest-ci --verbose
  Prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cruk-react-components
        uses: actions/checkout@v3
      - name: npm install
        run: npm ci --legacy-peer-deps
      - name: Test
        run: npm run prettier:debug
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cruk-react-components
        uses: actions/checkout@v3
      - name: npm install
        run: npm ci --legacy-peer-deps
      - name: Test
        run: npm run eslint:test
