name: "Test"
on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  PlaywrightTests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v6.0.0
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: ./package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Install dependencies for Playwright
        run: npx playwright install
      - name: Run Playwright tests
        run: npm run test-ct
      - name: Save traces
        continue-on-error: true
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: traces-playwright
          path: apps/fwa/test-results
          retention-days: 7
  Unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cruk-react-components
        uses: actions/checkout@v4
      - name: npm install
        run: npm ci
      - name: Test
        run: npm run node-test --verbose
  Prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cruk-react-components
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v6.0.0
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: ./package-lock.json
      - name: npm install
        run: npm ci
      - name: Test
        run: npm run prettier:debug
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cruk-react-components
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v6.0.0
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: ./package-lock.json
      - name: npm install
        run: npm ci
      - name: Test
        run: npm run eslint:test
  Chromatic:
    if: github.actor!= 'depbot'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history
      - name: Setup Node
        uses: actions/setup-node@v6.0.0
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: ./package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          # Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
