name: "Test"
on:
  pull_request:
    branches:
      - develop
      - master
jobs:
  Cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cruk-react-components
        uses: actions/checkout@v2.3.4
      - name: npm install
        run: docker-compose run npm ci
      - name: Bring up the server
        run: docker-compose up -d server
      - name: Test
        run: npm run cypress-headless
      - name: Work around our usage of Github storage
        if: failure()
        run: |
          mkdir output
          tar cvfj output/videos.tar.bz2 -C cypress/videos .
          tar cvfj output/screenshots.tar.bz2 -C cypress/screenshots .
          tar cvfj output/snapshots.tar.bz2 -C cypress/snapshots .
      - name: Upload Cypress output
        if: failure()
        uses: actions/upload-artifact@v2.2.4
        with:
          name: output
          path: output
  Jest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cruk-react-components
        uses: actions/checkout@v2.3.4
      - name: npm install
        run: docker-compose run npm ci
      - name: Test
        run: npm run jest-ci --verbose
  Prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cruk-react-components
        uses: actions/checkout@v2.3.4
      - name: npm install
        run: docker-compose run npm ci
      - name: Test
        run: npm run prettier:debug
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cruk-react-components
        uses: actions/checkout@v2.3.4
      - name: npm install
        run: docker-compose run npm ci
      - name: Test
        run: npm run eslint:test
  Percy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install dependencies
        run: npm install
      - name: Run Percy tests
        run: npm run percy
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
