name: "Test"
on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  Cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cruk-react-components
        uses: actions/checkout@v4
      - name: npm install
        run: npm ci
      - name: Test
        run: npm run cypress-headless
      - name: Work around our usage of Github storage
        if: failure()
        run: |
          mkdir output
          tar cvfj output/screenshots.tar.bz2 -C cypress/screenshots .
          tar cvfj output/snapshots.tar.bz2 -C cypress/snapshots .
      - name: Upload Cypress output
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: output
  Unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cruk-react-components
        uses: actions/checkout@v4
      - name: npm install
        run: npm ci
      - name: Test
        run: npm run node-test --verbose
  Prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cruk-react-components
        uses: actions/checkout@v4
      - name: npm install
        run: npm ci
      - name: Test
        run: npm run prettier:debug
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cruk-react-components
        uses: actions/checkout@v4
      - name: npm install
        run: npm ci
      - name: Test
        run: npm run eslint:test
  Chromatic:
    if: github.actor!= 'depbot'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history
      - name: Install dependencies
        run: npm ci
      - name: Publish to Chromatic
        uses: chromaui/action@v11
        with:
          # Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
