name: 'Test'
on:
  pull_request:
    branches:
      - develop
      - master
jobs:
  Cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cruk-react-components
        uses: actions/checkout@v1
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node_modules-
      - name: npm install
        run: docker-compose run npm clear cache && docker-compose run npm ci
      - name: Bring up the server
        run: docker-compose up -d server
      - name: Test
        run: docker-compose run cypress
      - name: Work around our usage of Github storage
        if: failure()
        run: |
          mkdir output
          tar cvfj output/videos.tar.bz2 -C cypress/videos .
          tar cvfj output/screenshots.tar.bz2 -C cypress/screenshots .
          tar cvfj output/snapshots.tar.bz2 -C cypress/snapshots .
      - name: Upload Cypress output
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: output
          path: output
